#!/bin/ ksh, bash, sh,dash        # these are executables for executing the shell script command 
echo                              # to print something
Sh or ./                          # before file to execute file
./                                # require persison 
Chmod                             # changing permissions for file
1st - permission for root user 
2nd - Permission for the group
3rd - Permission for you

7(magic number) : 777 (1st myself , 2nd my group , 3rd  for all users)
4:Read 
2:Write 
1:Ecexute

#Purpose of shell sripting in devops#
As Devops enggineer you have to do 
-	Infrastruchter management
-	Configuration mannagment
-	Code management e.g using git repository by using Linux
Learning bash scripting:
	Best Practices to write scripts
1.Always write meta data before script 
2.Running in debug mode (set -x) put in start
3.Exit script when there is an error (set -e)
4.Pipfail  (set -o)
